const GET_COUNTRIES = 'GET-COUNTRIES';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const GET_COUNTRY = 'GET_COUNTRY';
const CLEAN_DETAIL = 'CLEAN_DETAIL';
const COUNTRY_BY_NAME = 'COUNTRY_BY_NAME';
const CLEAN_COUNTRY = 'CLEAN_COUNTRY';
const CONTINENT_FILTER = 'CONTINENT_FILTER';
const ORDER_POPULATION = 'ORDER_POPULATION';
const ORDER_ALPHABETIC = 'ORDER_ALPHABETIC';
const CLEAN_FILTER_ORDER = 'CLEAN_FILTER_ORDER';
const POST_ACTIVITIES = 'POST_ACTIVITIES';
const ACTIVITIES_FILTER = 'ACTIVITIES_FILTER';


export {
    GET_ACTIVITIES,
    GET_COUNTRIES,
    GET_COUNTRY,
    CLEAN_DETAIL,
    COUNTRY_BY_NAME,
    CLEAN_COUNTRY,
    CONTINENT_FILTER,
    ORDER_POPULATION,
    ORDER_ALPHABETIC,
    CLEAN_FILTER_ORDER,
    POST_ACTIVITIES,
    ACTIVITIES_FILTER
};
